### PR TITLE
Add front end setup instructions

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by koudelka** [comment]
ah, thanks. :)

**Comment by koudelka** [comment]
jfyi, the `brunch` command is already handled internally by phoenix.

**Comment by lpil** [comment]
I'm used to it being so, but it didn't work when I tried it for some reason.

**Comment by koudelka** [comment]
hm, that's odd. are you running it in `dev`?

**Comment by lpil** [comment]
How can I tell? I just copied the command from the README. I'm used to using mix to start phoenix, and sadly don't really know how it works otherwise.

**Comment by koudelka** [comment]
Yeah, that'll start you up in `dev` mode by default. You can change the environment by prepending `MIX_ENV=<env>` to the command.

I wonder if it's getting set in your shell somehow. Does `env | grep "MIX_ENV"` show anything?

**Comment by lpil** [comment]
Nope, it's not that. I can't seem to reproduce it now, so lets just assume I did something wrong. ;)

Thanks Michael

**Comment by koudelka** [comment]
Ah, my favorite and most worrisome kind of bug. :D

**Pull request merged**
